### ISSUE TITLE
Using OpenAI own API KEY

### ISSUE THREAD

**Issue by LCBO** [OpenAssistantGPT/OpenAssistantGPT#436]
Hello
I have 2 questions:

1. Is it possible with minimal changes to use my own OpenAI key so all my users to use mine?
Of course the other restrictions related to the plans will remain in place. 
As for me i consider that will be easier for my users to use my own api key

2. I created 2-3, etc chatbots but i want to offer access to them to my users, part of some subscription plans.

If it can be done via custom coding and payment I am eagerly to discuss

**Comment by marcolivierbouch** [comment]
Hello,

Do you have your own fork of the project or you are using or hosted version?

**Comment by LCBO** [comment]
hi
Hosted version.

**Comment by marcolivierbouch** [comment]
It can be done using custom code but it is probably wont be something we will add in the main version
