### ISSUE TITLE
File from Assistants file-search is unavailable to the chatbot

### ISSUE THREAD

**Issue by dhoegerlETM** [OpenAssistantGPT/OpenAssistantGPT#486]
**Describe the bug**
Our connected OpenAI Assistant uses the file-search with an uploaded MD file and an according context to access that provided file for dedicated requests. I cannot tell since when, but currently the chatbot give that statement within it's reply:
It seems that the <XYZ> file is not available.

When I use the Playground of the OpenAI Assistant directly, all works and no complains about unavailable files.

**Expected behavior**
Not only attached files to the chat-thread, but also files from the file-search vector-store of the assistant shall be accessible.

**Comment by dhoegerlETM** [comment]
@marcolivierbouch this is (again) of high priority for us - please have a look there. Thank you!

**Comment by dhoegerlETM** [comment]
@marcolivierbouch now just one hour later without any change on our end it seems to be process the files from the Assistant context again as intended. Any idea for that nondeterministic behavior?

**Comment by marcolivierbouch** [comment]
Hello @dhoegerlETM,

File search works on our chatbot, on the main page.

![image](https://github.com/user-attachments/assets/d380467f-ca0c-4664-ad4e-bc8cd78a41b2)
 
 Do you have an imported assistant or you created it using our app?
 
 Also for emergency it is better to contact us using our support email .

**Comment by marcolivierbouch** [comment]
We havent made much change on the chat this morning 8-9 hours ago. This could be an issue on OpenAI side
