### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by danielehrhardt** [OpenAssistantGPT/OpenAssistantGPT#489]
Can someone tell why this project is dead?

**Comment by marcolivierbouch** [comment]
The project isnt dead we are mostly working on our sdk https://github.com/OpenAssistantGPT/chatbot-sdk than the platform itself and we focus on more enterprise features on our closed source platform.

**Comment by Korayem** [comment]
@marcolivierbouch amazing project.  I am learning a lot!

Can you add an example on how to best handle function calling, say `getweather`? thanks

**Comment by marcolivierbouch** [comment]
> @marcolivierbouch amazing project. I am learning a lot!
> 
> Can you add an example on how to best handle function calling, say `getweather`? thanks

If you want to add custom actions I would highly recommend to look at our https://github.com/OpenAssistantGPT/chatbot-sdk chatbot sdk. You'll have to update the /api/assistant call to add your custom actions
