### ISSUE TITLE
Download document failed

### ISSUE THREAD

**Issue by tobygjones** [OpenAssistantGPT/OpenAssistantGPT#490]
I request for the chatbot to provide a download of a file it had access to, the chatbot complied and create a link, although this link just sent me to a new tab with a blank chatbot on it. 

Here is the message log:

    ],
    "thread_Gh5YQ0hqRHODM5nHLNmaWPz0": [
      {
        "id": "cm2kchgoz000f9fnmlxuv3oal",
        "message": "The download link just send me to another tab with a chatbot on it",
        "response": "I apologize for the inconvenience. It seems there was an issue with the link. Let me provide you with the correct way to download the Warwickshire College handbook. \n\nYou can download the handbook directly [here](sandbox:/mnt/data/Warwickshire-College-Student-Handbook-V16.0-November-2023-uoWvjeF5bJAYphAygsxEdZExCNl7JT.docx).\n\nPlease try this link to access the document. If you encounter any other issues or have further questions, let me know!",
        "createdAt": "2024-10-22T11:11:08.483Z",
        "threadId": "thread_Gh5YQ0hqRHODM5nHLNmaWPz0",
        "userIP": "202.7.251.66"
      },
      {
        "id": "cm2kcfvly00099fnmmoxwlsa2",
        "message": "Can I download the Warwickshire College handbook?",
        "response": "Yes, you can download the Warwickshire College Student Handbook. Here is the link to download the document:\n\n[Download Warwickshire College Student Handbook](sandbox:/mnt/data/Warwickshire-College-Student-Handbook-V16.0-November-2023-uoWvjeF5bJAYphAygsxEdZExCNl7JT.docx)\n\nIf you have any further questions about the handbook or its contents, feel free to ask!",
        "createdAt": "2024-10-22T11:09:54.502Z",
        "threadId": "thread_Gh5YQ0hqRHODM5nHLNmaWPz0",
        "userIP": "202.7.251.66"
      

**Desktop (please complete the following information):**
 - OS: Mac OS 14.1
 - Browser - ARC
 - Version 1.63.1

**Comment by marcolivierbouch** [comment]
Hello,

it is a feature in our backlog, I will let you know when it is delivered. It should be done in few weeks.

**Comment by marcolivierbouch** [comment]
![image](https://github.com/user-attachments/assets/cf6a7f54-2d20-4e08-90e9-df7f83b36d48)
https://www.openassistantgpt.io/changelog

It is now possible to add a feature to display file references and the user can click on the click to download the file. Does this fix your issue?
